### ISSUE TITLE
macOS update throws PermissionError exception

### ISSUE THREAD

**Issue by androidWG** [AndroidWG/OpenRCT2SilentLauncher#3]
When the program tries to delete the OpenRCT2.app folder inside /Applications, it gets a `PermissionError` exception:
```
Preparing to install file OpenRCT2-0.3.3-macos-x86-64.zip
Uncaught exception
Traceback (most recent call last):
  File "/Users/samuel/Repos/Corkscrew/main.py", line 52, in <module>
    main()
  File "/Users/samuel/Repos/Corkscrew/main.py", line 46, in main
    download_handler.update_openrct2()
  File "/Users/samuel/Repos/Corkscrew/handler.py", line 87, in update_openrct2
    shutil.rmtree(self.mac_app_path)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'OpenRCT2'
```

We could run the app as sudo from the LaunchAgent, but that would be a massive security hole (someone changes the Corkscrew executable to anything else and no password will be asked), so the main solution would be to send a notification for the user to input the password whenever ORCT2 needs to be installed.

So in practice, we'd need either another packaged script to exclusively install ORCT2 as sudo or use `main.py` with a flag like `--install <path-to-installer>` launched as sudo.

**Comment by androidWG** [comment]
A better solution might be to just move the OpenRCT2.app folder to the Trash Bin instead of deleting it, since that likely requires no elevation.
